title: Degrowth Journal

exclude:
  - README.md

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "volumes"
    values:
      layout: "volume"
  -
    scope:
      path: ""
      type: "articles"
    values:
      layout: "article"

collections:
  pages:
    output: true
  volumes:
    output: true
    permalink: /volumes/:name
  articles:
    output: true
    permalink: /articles/:name

sass:
    style: compressed

plugins:
  - jekyll-minifier

jekyll-minifier:
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_intertag_spaces: true
  remove_comments: true
  compress_css: false
  compress_javascript: true
