title: Degrowth Journal
url: https://degrowthjournal.org

exclude:
  - README.md

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "volumes"
    values:
      layout: "volume"
  -
    scope:
      path: ""
      type: "articles"
    values:
      layout: "article"
  -
    scope:
      path: ""
      type: "researchers"
    values:
      layout: "researcher"

collections:
  pages:
    output: true
  volumes:
    output: true
    permalink: /volumes/:name
  articles:
    output: true
    permalink: /articles/:name
  researchers:
    output: true
    permalink: /researchers/:name

sass:
    style: compressed

jekyll-minifier:
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_intertag_spaces: true
  remove_comments: true
  compress_css: false
  compress_javascript: true

picture:
  ignore_missing_images: true
